package com.autoservice.identityservice.exception;

public enum ErrorCode {

    VALIDATION_ERROR,

    USERNAME_ALREADY_EXISTS,
    PHONE_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,

    USER_NOT_FOUND,

    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,

    ACCOUNT_PENDING_ACTIVATION,
    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,

    ACCESS_DENIED,
    INTERNAL_SERVER_ERROR
}