package com.autoservice.identityservice.exception;

public enum ErrorCode {

    VALIDATION_ERROR,

    USERNAME_ALREADY_EXISTS,
    PHONE_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,

    USER_NOT_FOUND,
    MECHANIC_PROFILE_NOT_FOUND,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,

    ACCOUNT_PENDING_ACTIVATION,
    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,

    CANNOT_UPDATE_OWN_ACCOUNT,
    INVALID_ACCOUNT_STATUS,

    PROFILE_UPDATE_NO_CHANGES,
    CURRENT_PASSWORD_INCORRECT,
    PASSWORD_CONFIRMATION_MISMATCH,
    NEW_PASSWORD_SAME_AS_CURRENT,

    INTERNAL_SERVER_ERROR
}